// Constantes para la sección de proyectos
export const PROJECTS = [
  {
    id: 1,
    title: 'stride-agent-showcase',
    description: 'TypeScript/Node.js coding-agent runtime with policy-gated tools, allow/ask/deny permissions, audit logging, secret redaction, fake/OpenAI-compatible providers and plugin loading.',
    technologies: ['TypeScript', 'MCP', 'OpenAI API'],
    image: '',
    githubUrl: 'https://github.com/RafaGonzalezDev/stride-agent-showcase',
    liveUrl: '',
    featured: true,
    year: '2025',
    category: 'AI Developer Tooling',
    highlights: [
      'Policy-gated tools with allow/ask/deny permissions',
      'Audit logging and secret redaction',
      'Fake/OpenAI-compatible providers',
      'Plugin loading system',
    ],
  },
  {
    id: 2,
    title: 'local-llm-inference-lab',
    description: 'Local inference lab with llama.cpp-compatible serving, GGUF profiles, OpenAI-compatible API, OpenWebUI and tuning for context size, token budget, batch/micro-batch and CPU/GPU offload.',
    technologies: ['llama.cpp', 'GGUF', 'OpenAI API'],
    image: '',
    githubUrl: 'https://github.com/RafaGonzalezDev/local-llm-inference-lab',
    liveUrl: '',
    featured: true,
    year: '2025',
    category: 'Local LLM / Model Serving',
    highlights: [
      'llama.cpp-compatible serving with GGUF profiles',
      'OpenAI-compatible API',
      'OpenWebUI integration',
      'Context sizing, token budget, CPU/GPU offload',
    ],
  },
  {
    id: 3,
    title: 'dotfiles-opencode-showcase',
    description: 'Role/team-based OpenCode profile installer with a TypeScript/Ink CLI, agentic workflows, transactional backups/rollback and managed configuration verification.',
    technologies: ['TypeScript', 'Ink', 'Bash'],
    image: '',
    githubUrl: 'https://github.com/RafaGonzalezDev/dotfiles-opencode-showcase',
    liveUrl: '',
    featured: true,
    year: '2025',
    category: 'Developer Tooling',
    highlights: [
      'TypeScript/Ink CLI for profile management',
      'Automated agentic workflows',
      'Transactional backups/rollback',
      'Managed configuration verification',
    ],
  },
  {
    id: 4,
    title: 'dotfiles-pi-showcase',
    description: 'Lightweight Pi extension showcase with MCP tool loading, exact-URL web fetch, policy-based security guardrails and compact renderers for coding-agent workflows.',
    technologies: ['TypeScript', 'MCP', 'Node.js'],
    image: '',
    githubUrl: 'https://github.com/RafaGonzalezDev/dotfiles-pi-showcase',
    liveUrl: '',
    featured: true,
    year: '2025',
    category: 'Coding Agent Extensions',
    highlights: [
      'MCP tool loading',
      'Exact-URL web fetch',
      'Policy-based security guardrails',
      'Compact renderers for coding-agent workflows',
    ],
  },
  {
    id: 5,
    title: 'angular-i18n-translator',
    description: 'Node.js CLI for automating Angular XLF i18n with LLMs, batch processing, interpolation preservation, placeholder validation and multi-provider support.',
    technologies: ['TypeScript', 'Angular', 'LLM APIs'],
    image: '',
    githubUrl: 'https://github.com/RafaGonzalezDev/angular-i18n-translator',
    liveUrl: '',
    featured: true,
    year: '2024',
    category: 'Developer Tooling',
    highlights: [
      'Automated Angular XLF i18n with LLMs',
      'Batch processing of translations',
      'Interpolation preservation',
      'Placeholder validation and multi-provider support',
    ],
  },
  {
    id: 6,
    title: 'cv-typewriter',
    description: 'Data-first CV editor built with React/Vite, bilingual JSON content, paginated A4 preview, Markdown links and PDF export for version-controlled ATS-friendly content.',
    technologies: ['React', 'Vite', 'Tailwind CSS'],
    image: '',
    githubUrl: 'https://github.com/RafaGonzalezDev/cv-typewriter',
    liveUrl: '',
    featured: true,
    year: '2024',
    category: 'Web Application',
    highlights: [
      'Live JSON editor with real-time CV updates',
      'Bilingual JSON content (ES/EN)',
      'Paginated A4 preview',
      'Markdown support and PDF export',
      'RenderCV-compatible schema',
    ],
  },
];
