// Constantes para la sección de proyectos
export const PROJECTS = [
  {
    id: 1,
    title: 'stride-agent-showcase',
    description: 'TypeScript/Node.js coding-agent runtime with policy-gated tools, allow/ask/deny permissions, audit logging, secret redaction, fake/OpenAI-compatible providers and plugin loading.',
    technologies: ['TypeScript', 'MCP', 'OpenAI API'],
    image: '',
    githubUrl: 'https://github.com/RafaGonzalezDev/stride-agent-showcase',
    liveUrl: '',
    featured: true,
    year: '2025',
    category: 'AI Developer Tooling',
    highlights: [
      'Policy-gated tools with allow/ask/deny permissions',
      'Audit logging and secret redaction',
      'Fake/OpenAI-compatible providers',
      'Plugin loading system',
    ],
  },
  {
    id: 2,
    title: 'mcp-schema-runner',
    description: 'Local developer tool for debugging stdio MCP servers with tool schema inspection, manual tool calls, raw request/response/error traces and OpenCode + Hermes config normalization.',
    technologies: ['TypeScript', 'MCP', 'React'],
    image: '',
    githubUrl: 'https://github.com/RafaGonzalezDev/mcp-schema-runner',
    liveUrl: '',
    featured: true,
    year: '2026',
    category: 'AI Developer Tooling',
    highlights: [
      'Tool schema inspection for stdio MCP servers',
      'Manual tool calls with custom arguments',
      'Raw request / response / error trace inspection',
      'Config normalization for OpenCode and Hermes formats',
    ],
  },
  {
    id: 3,
    title: 'dotfiles-opencode-showcase',
    description: 'Role/team-based OpenCode profile installer with a TypeScript/Ink CLI, agentic workflows, transactional backups/rollback and managed configuration verification.',
    technologies: ['TypeScript', 'Ink', 'Bash'],
    image: '',
    githubUrl: 'https://github.com/RafaGonzalezDev/dotfiles-opencode-showcase',
    liveUrl: '',
    featured: true,
    year: '2025',
    category: 'Developer Tooling',
    highlights: [
      'TypeScript/Ink CLI for profile management',
      'Automated agentic workflows',
      'Transactional backups/rollback',
      'Managed configuration verification',
    ],
  },
  {
    id: 4,
    title: 'dotfiles-pi-showcase',
    description: 'Lightweight Pi extension showcase with MCP tool loading, exact-URL web fetch, policy-based security guardrails and compact renderers for coding-agent workflows.',
    technologies: ['TypeScript', 'MCP', 'Node.js'],
    image: '',
    githubUrl: 'https://github.com/RafaGonzalezDev/dotfiles-pi-showcase',
    liveUrl: '',
    featured: true,
    year: '2025',
    category: 'Coding Agent Extensions',
    highlights: [
      'MCP tool loading',
      'Exact-URL web fetch',
      'Policy-based security guardrails',
      'Compact renderers for coding-agent workflows',
    ],
  },
  {
    id: 5,
    title: 'angular-i18n-translator',
    description: 'Node.js CLI for automating Angular XLF i18n with LLMs, batch processing, interpolation preservation, placeholder validation and multi-provider support.',
    technologies: ['TypeScript', 'Angular', 'LLM APIs'],
    image: '',
    githubUrl: 'https://github.com/RafaGonzalezDev/angular-i18n-translator',
    liveUrl: '',
    featured: true,
    year: '2024',
    category: 'Developer Tooling',
    highlights: [
      'Automated Angular XLF i18n with LLMs',
      'Batch processing of translations',
      'Interpolation preservation',
      'Placeholder validation and multi-provider support',
    ],
  },
  {
    id: 6,
    title: 'agentic-pr-reviewer-action',
    description: 'Agentic GitHub Action for diff-scoped Pull Request reviews using OpenAI-compatible LLM endpoints, focused on CI/CD automation and actionable code-review feedback.',
    technologies: ['GitHub Actions', 'Node.js', 'LLM APIs'],
    image: '',
    githubUrl: 'https://github.com/RafaGonzalezDev/agentic-pr-reviewer-action',
    liveUrl: '',
    featured: true,
    year: '2026',
    category: 'AI Code Review Automation',
    highlights: [
      'Diff-scoped Pull Request reviews',
      'OpenAI-compatible LLM endpoint support',
      'GitHub Actions CI/CD integration',
      'Actionable automated code-review feedback',
    ],
  },
];
