// Constantes para la sección de proyectos
export const PROJECTS = [
  {
    id: 1,
    title: 'YouTube Transcript CLI',
    description: 'CLI tool to download YouTube video transcripts in Markdown format. It extracts video IDs, downloads transcripts in specified languages, and saves them to .md files.',
    technologies: ['Python', 'youtube-transcript-api'],
    image: '',
    githubUrl: 'https://github.com/RafaGonzalezDev/youtube-transcript-cli',
    liveUrl: '',
    featured: true,
    year: '2024',
    category: 'CLI Tool',
    highlights: ['Extracts YouTube video ID from any URL format', 'Downloads transcript in the specified language', 'Formats transcript and saves it to a .md file'],
  },
  {
    id: 2,
    title: 'WCAG Design System',
    description: 'A comprehensive color palette generator and accessibility testing tool designed to help developers and designers create WCAG 2.2 compliant color combinations for web applications.',
    technologies: ['React', 'TypeScript', 'Shadcn/UI', 'Tailwind CSS', 'Vite'],
    image: '',
    githubUrl: 'https://github.com/RafaGonzalezDev/wcag_design',
    liveUrl: '',
    featured: true,
    year: '2024',
    category: 'Web Application',
    highlights: [
      'Real-time WCAG Validation with instant feedback on contrast ratios and compliance levels',
      'Custom Color Creation with interactive color pickers and hex input support',
      'Accessibility Scoring with visual progress indicators showing compliance percentage',
      'Expert-Curated Collections of pre-defined palettes tested for WCAG 2.1 AA standards',
      'Live Preview environment to see how colors perform with different text sizes and analyze detailed compliance reports',
    ],
  },
  {
    id: 3,
    title: 'HiLink',
    description:
      'Frontend design of a travel and adventure application implemented with CSS-in-JS. Best development practices were applied to create a modern and responsive user interface, making use of reusable components and a scalable architecture.',
    technologies: ['React', 'Tailwind CSS', 'Vite', 'JavaScript'],
    image: '/projects/document-platform.jpg',
    githubUrl: 'https://github.com/RafaGonzalezDev/hilink',
    liveUrl: 'https://document-platform.example.com',
    featured: true,
    year: '2024',
    category: 'Enterprise Web Development',
    highlights: ['Scalable micro frontend architecture', 'Advanced permissions system', 'Optimized document loading and search'],
  },
  {
    id: 4,
    title: 'HooBank',
    description:
      'Frontend implementation of a modern banking platform using CSS-in-JS for component styling. The project was developed following web development best practices, with a focus on accessibility, performance, and fluid user experience.',
    technologies: ['React', 'Tailwind CSS', 'Vite', 'JavaScript'],
    image: '/projects/cultural-events.jpg',
    githubUrl: 'https://github.com/RafaGonzalezDev/hoobank',
    liveUrl: 'https://cultural-events.example.com',
    featured: true,
    year: '2023',
    category: 'Full Stack Application',
    highlights: ['Personalized recommendation system', 'Payment gateway integration', 'Real-time notifications'],
  },
];